/**
 * @file src/types/index.ts
 * @description Core type definitions for Junction Generator Coin (JGC).
 *
 * ARCHITECTURE COMPARISON — Bitcoin vs JGC
 * ─────────────────────────────────────────
 * Bitcoin's block.h defines CBlockHeader with:
 *   int32_t  nVersion;
 *   uint256  hashPrevBlock;
 *   uint256  hashMerkleRoot;
 *   uint32_t nTime;
 *   uint32_t nBits;          ← compact difficulty target
 *   uint32_t nNonce;         ← brute-force search value
 *
 * JGC replaces the nNonce search with a ComputeProof: a ZK-SNARK attesting
 * that the miner performed a specific, verifiable AI tensor computation
 * (forward pass, gradient update, or folding simulation).  The "work" is
 * measured in TFLOPS-seconds rather than SHA256 hash attempts.
 *
 * Supply schedule deviates from Bitcoin as follows:
 *   BTC: 50 BTC/block → halves (÷2) every 210,000 blocks → cap 21 M BTC
 *   JGC: 50 JGC/block → quarters (×0.75) every 105,000 blocks → cap 21 M JGC
 *
 * The infinite geometric convergence:
 *   S = a / (1 - r) = 5,250,000 / (1 - 0.75) = 21,000,000 JGC  ✓
 *
 * Epoch payout (every 144 blocks = 1 day):
 *   Total daily emission = 50 × 144 = 7,200 JGC distributed pro-rata
 *   by each miner's verified TFLOPS contribution within the epoch.
 */

// ─────────────────────────────────────────────────────────────────────────────
// Primitive Aliases (typed for safety, stored as hex strings in serialization)
// ─────────────────────────────────────────────────────────────────────────────

/** 32-byte hash represented as a 64-character lowercase hex string. */
export type Hash256 = string;

/** 33-byte compressed secp256k1 public key (66 hex chars). */
export type PublicKey = string;

/** 64-byte DER-encoded secp256k1 signature (128 hex chars). */
export type Signature = string;

/** Miner address — Base58Check encoded P2PKH, identical format to Bitcoin. */
export type Address = string;

/** Block height, zero-indexed from genesis. */
export type BlockHeight = number;

/** UNIX timestamp in seconds, same semantic as nTime in Bitcoin headers. */
export type UnixTimestamp = number;

/** Canonical JGC amount in base units (1 JGC = 10^16 units). BigInt because the
 *  supply (21M × 10^16 = 2.1e23) overflows a 64-bit integer. */
export type JGCSatoshis = bigint;

// ─────────────────────────────────────────────────────────────────────────────
// ZK-Proof Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * The computational task category the miner executed.
 * These map to different ZK-SNARK circuit families.
 */
export enum ComputeTaskType {
  /** Standard AI forward-pass inference (e.g. LLM token generation). */
  AI_INFERENCE   = "AI_INFERENCE",
  /** Gradient computation + parameter update for an AI training step. */
  AI_TRAINING    = "AI_TRAINING",
  /** Protein-folding simulation (Folding@Home compatible format). */
  FOLD_SIM       = "FOLD_SIM",
  /** Molecular dynamics / climate model tick (scientific fallback broker). */
  SCI_COMPUTE    = "SCI_COMPUTE",
  /** Arbitrary commercial compute task verified by third-party task issuer. */
  COMMERCIAL     = "COMMERCIAL",
}

/**
 * ComputeProof — the cryptographic heart of Proof-of-Useful-Compute (PoUC).
 *
 * COMPARISON TO BITCOIN pow.cpp:
 *   Bitcoin's CheckProofOfWork() simply calls:
 *     hash.GetHex() <= bnTarget.GetHex()
 *   i.e., the SHA256d hash of the 80-byte header must be numerically
 *   below the target stored in nBits.
 *
 *   JGC's equivalent (validateComputeProof in consensus/validation.ts):
 *     1. Deserialise the Groth16 proof from `proofBytes`.
 *     2. Reconstruct the public inputs from `taskCommitment` + `tflopsWeight`.
 *     3. Call the Rust WASM verifier (groth16_verify) — O(1) pairing check.
 *     4. Assert tflopsWeight >= currentEpochDifficultyTarget.
 *
 *   The "hash target" analogy: tflopsWeight must exceed a TFLOPS-derived
 *   difficulty threshold, dynamically retargeted every 2016 blocks
 *   (analogous to Bitcoin's every-2016-block difficulty adjustment).
 */
export interface ComputeProof {
  /** SHA-256 commitment to the specific task parameters (model weights hash,
   *  dataset batch hash, or folding protein PDB hash). Acts like the nonce
   *  seed — unique per miner attempt, commits to real computational input. */
  taskCommitment: Hash256;

  /** Groth16 ZK-SNARK proof bytes (256 bytes uncompressed A‖B‖C over BN254),
   *  base64-encoded. Generated by the miner's local proving system
   *  (SnarkJS / Bellman / Arkworks). */
  proofBytes: string;

  /** Verification key identifier — references the published circuit VK stored
   *  on-chain at genesis or updated via governance. Analogous to Bitcoin's
   *  algorithm version in nVersion. */
  circuitId: string;

  /** The public input vector for the SNARK circuit.  At minimum:
   *   [0]: taskCommitment (as field element)
   *   [1]: tflopsWeight   (as field element)
   *   [2]: epochBlockIndex (prevents proof replay across epochs) */
  publicInputs: string[];  // field elements as decimal strings

  /** Claimed TFLOPS-seconds of compute, verified by the circuit's output.
   *  This is the PoUC analog of the numeric hash difficulty value. */
  tflopsWeight: number;

  /** Task type — selects the circuit family for proof verification. */
  taskType: ComputeTaskType;

  /** ISO 8601 timestamp when the computation was initiated (informational,
   *  used by the broker to expire stale task bids). */
  computeStartedAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Block Structure
// ─────────────────────────────────────────────────────────────────────────────

/**
 * BlockHeader — serializable, 160-byte fixed-size header.
 *
 * BITCOIN COMPARISON (80-byte header):
 *   nVersion(4) | hashPrevBlock(32) | hashMerkleRoot(32) | nTime(4) | nBits(4) | nNonce(4)
 *
 * JGC HEADER (160 bytes):
 *   version(4) | prevHash(32) | merkleRoot(32) | computeRoot(32) | epochRoot(32)
 *   | timestamp(8) | difficultyBits(4) | nonce(4) | height(8) | reserved(4)
 *
 * The nNonce is retained for minor entropy/anti-spam but the primary
 * proof-of-work is the computeRoot — a Merkle root of all ComputeProofs
 * submitted by miners in this block slot.
 */
export interface BlockHeader {
  /** Protocol version.  JGC v1 = 0x01000000. */
  version: number;

  /** Hash of the previous block header (same semantics as Bitcoin's hashPrevBlock). */
  prevHash: Hash256;

  /** Merkle root of all transactions in this block (same as Bitcoin hashMerkleRoot). */
  merkleRoot: Hash256;

  /** Merkle root of all ComputeProofs included in this block.
   *  This is JGC-specific — absent in Bitcoin.  Validates the PoUC work. */
  computeRoot: Hash256;

  /** Merkle root of the epoch accumulator state (running tally of per-miner
   *  TFLOPS contributions since last epoch boundary). */
  epochRoot: Hash256;

  /** UNIX timestamp in seconds — same semantic as Bitcoin's nTime.
   *  Nodes reject headers with timestamps > median(last 11) + 7200 seconds. */
  timestamp: UnixTimestamp;

  /** Compact target encoding (same nBits format as Bitcoin).
   *  Encodes the minimum required tflopsWeight instead of hash target. */
  difficultyBits: number;

  /** Small nonce for miner differentiation when two miners submit identical
   *  compute tasks.  Not the primary work source — contrast with Bitcoin where
   *  nNonce IS the entire proof-of-work. */
  nonce: number;

  /** Block height.  Embedded in header (unlike Bitcoin) for fast SPV queries. */
  height: BlockHeight;
}

/**
 * A miner's compute contribution record, included in each block's
 * computeProofs array and Merkle-committed via computeRoot.
 */
export interface MinerComputeContribution {
  /** Miner's JGC address — payout target at epoch settlement. */
  minerAddress: Address;

  /** The ZK proof attesting this miner's compute work. */
  proof: ComputeProof;

  /** BLS/Schnorr signature over SHA256(taskCommitment ∥ minerAddress ∥ blockHeight). */
  signature: Signature;

  /** Miner's public key for signature verification. */
  publicKey: PublicKey;
}

/**
 * Full Block — analogous to Bitcoin's CBlock.
 *
 * Bitcoin CBlock = CBlockHeader + vector<CTransaction>
 * JGC Block      = BlockHeader  + transactions + computeProofs + epochState
 */
export interface Block {
  /** The 160-byte serializable header. */
  header: BlockHeader;

  /** Ordered list of JGC transactions (UTXO model, same as Bitcoin). */
  transactions: Transaction[];

  /** All miner compute contributions for this block slot.
   *  Unlike Bitcoin's single miner, JGC supports multi-party PoUC
   *  — all provers contributing in the 10-minute window are included. */
  computeProofs: MinerComputeContribution[];

  /** Snapshot of epoch accumulator at this block boundary. */
  epochState: EpochState;
}

// ─────────────────────────────────────────────────────────────────────────────
// Transaction Types (UTXO model — same as Bitcoin)
// ─────────────────────────────────────────────────────────────────────────────

export interface OutPoint {
  txid: Hash256;
  vout: number;
}

export interface TxInput {
  prevOut: OutPoint;
  scriptSig: string;   // hex-encoded
  sequence: number;    // 0xFFFFFFFF default
  witness?: string[];  // SegWit-equivalent (JGC supports native witness)
}

export interface TxOutput {
  value: JGCSatoshis;
  scriptPubKey: string;  // hex-encoded P2PKH or P2WPKH
}

export interface Transaction {
  version: number;
  inputs: TxInput[];
  outputs: TxOutput[];
  locktime: number;
  /** JGC-specific: if this tx carries a broker payment, reference the task. */
  brokerTaskRef?: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Epoch State (24-hour payout accumulator)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * EpochState — tracks the rolling 144-block (24h) contribution window.
 *
 * Unlike Bitcoin where each block independently pays a coinbase reward to one
 * miner, JGC accumulates all TFLOPS contributions across 144 blocks and
 * settles proportional payouts at the epoch boundary (every 144th block).
 *
 * Settlement formula:
 *   minerPayout(m) = epochRewardPool × (minerTFLOPS(m) / totalEpochTFLOPS)
 *
 * where epochRewardPool = blockReward(currentEra) × 144
 */
export interface EpochState {
  /** Block height at which this epoch started (always a multiple of 144). */
  epochStartHeight: BlockHeight;

  /** Current block index within the epoch [0, 143]. */
  epochBlockIndex: number;

  /** Total accumulated TFLOPS-seconds verified in this epoch so far. */
  totalEpochTFLOPS: number;

  /** Per-miner TFLOPS accumulator: address → TFLOPS-seconds. */
  minerContributions: Map<Address, number>;

  /** Accumulated JGC reward pool for this epoch (in satoshis).
   *  Incremented by blockReward each block; paid out at epoch boundary. */
  pendingRewardPool: JGCSatoshis;

  /** UNIX timestamp of epoch start block. */
  epochStartTime: UnixTimestamp;
}

// ─────────────────────────────────────────────────────────────────────────────
// Emission Schedule Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Describes one "era" in the JGC emission schedule.
 *
 * BITCOIN COMPARISON:
 *   Bitcoin: reward(n) = floor(50e8 / 2^n) satoshis, n = floor(height/210000)
 *   JGC:     reward(n) = floor(50e8 × 0.75^n) satoshis, n = floor(height/105000)
 *
 *   Era 0:  50.000000000 JGC × 105,000 = 5,250,000 JGC
 *   Era 1:  37.500000000 JGC × 105,000 = 3,937,500 JGC
 *   Era 2:  28.125000000 JGC × 105,000 = 2,953,125 JGC
 *   ...
 *   Sum → 5,250,000 / (1 - 0.75) = 21,000,000 JGC  (geometric series)
 */
export interface EmissionEra {
  eraIndex: number;
  startHeight: BlockHeight;
  endHeight: BlockHeight;       // startHeight + 105,000 - 1
  blockRewardSatoshis: JGCSatoshis;
  dailyEmissionJGC: number;     // informational: blockReward × 144 / 1e16
  totalEraSupply: JGCSatoshis;  // blockReward × 105,000
}

// ─────────────────────────────────────────────────────────────────────────────
// Difficulty Adjustment
// ─────────────────────────────────────────────────────────────────────────────

/**
 * DifficultyTarget — PoUC equivalent of Bitcoin's nBits.
 *
 * BITCOIN: nBits encodes a 256-bit hash target T such that SHA256d(header) < T.
 *
 * JGC: difficultyBits encodes a minimum TFLOPS-seconds threshold T such that
 *      sum(tflopsWeight for all proofs in block) >= T.
 *
 * Retargeting window: every 2016 blocks (same as Bitcoin's 2-week window).
 * Formula: newTarget = oldTarget × (actualTimespan / expectedTimespan)
 *          where expectedTimespan = 2016 × 600 seconds = 1,209,600 s
 *          Clamped to 1/4 × old ≤ new ≤ 4 × old (same clamp as Bitcoin).
 */
export interface DifficultyTarget {
  /** Compact bits encoding (same format as Bitcoin's nBits). */
  compactBits: number;

  /** Expanded TFLOPS-seconds minimum for a valid block. */
  minTFLOPS: number;

  /** Block height at which this target became active. */
  activationHeight: BlockHeight;
}

// ─────────────────────────────────────────────────────────────────────────────
// Compute Broker Types
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A bid from a commercial entity or scientific platform wanting compute time.
 * The broker ranks bids by price per TFLOPS-hour and routes idle nodes.
 */
export interface ComputeBid {
  bidId: string;
  bidderAddress: Address;
  taskType: ComputeTaskType;
  /** Maximum price bidder will pay, in JGC satoshis per TFLOPS-hour. */
  pricePerTFLOPSHour: JGCSatoshis;
  /** Minimum TFLOPS capacity required (screen out underpowered nodes). */
  minTFLOPSRequired: number;
  /** Total TFLOPS-hours requested. */
  totalTFLOPSHours: number;
  /** Task payload hash — content-addressed task bundle (model weights, dataset). */
  taskPayloadHash: Hash256;
  /** Bid expiry as UNIX timestamp. */
  expiresAt: UnixTimestamp;
  /** Whether this is a scientific fallback (Folding@Home etc.) — lower priority. */
  isFallback: boolean;
}

/**
 * Assignment record: a specific node assigned to a specific bid's work unit.
 */
export interface ComputeAssignment {
  assignmentId: string;
  bidId: string;
  nodePublicKey: PublicKey;
  assignedTFLOPS: number;
  startedAt: UnixTimestamp;
  deadlineAt: UnixTimestamp;
  /** ZK proof submitted upon task completion — verified before payment release. */
  completionProof?: ComputeProof;
  status: "PENDING" | "IN_PROGRESS" | "COMPLETED" | "FAILED" | "EXPIRED";
}

// ─────────────────────────────────────────────────────────────────────────────
// Network / P2P Types
// ─────────────────────────────────────────────────────────────────────────────

export enum MessageType {
  VERSION       = "VERSION",
  VERACK        = "VERACK",
  INV           = "INV",
  GETDATA       = "GETDATA",
  BLOCK         = "BLOCK",
  TX            = "TX",
  GETBLOCKS     = "GETBLOCKS",
  GETHEADERS    = "GETHEADERS",
  HEADERS       = "HEADERS",
  PING          = "PING",
  PONG          = "PONG",
  COMPUTE_PROOF = "COMPUTE_PROOF",   // JGC-specific: propagate new proof
  EPOCH_SETTLE  = "EPOCH_SETTLE",    // JGC-specific: epoch settlement tx
  BROKER_BID    = "BROKER_BID",      // JGC-specific: new compute bid
}

export interface PeerMessage {
  type: MessageType;
  payload: unknown;
  timestamp: UnixTimestamp;
  senderPublicKey: PublicKey;
  signature: Signature;
}

export interface NodeConfig {
  listenPort: number;
  rpcPort: number;
  networkMagic: number;       // 0xD9B4BEF9 for mainnet (same concept as Bitcoin)
  maxPeers: number;
  minerAddress?: Address;
  enableBroker: boolean;
  junctionGeneratorMode: boolean;  // Use compute for internal JG AI cluster first
}
