steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-f', 'deploy/monitor/Dockerfile', '-t', '${_IMAGE}', '.']
images: ['${_IMAGE}']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: 900s
