blank_issues_enabled: false
contact_links:
  - name: JunctionGenerator Community
    url: https://thinktank.ottomator.ai/c/JunctionGenerator/30
    about: Please ask questions and start conversations about JunctionGenerator here in the oTTomator Think Tank!